name: Rebuild request

on:
  repository_dispatch:
    types: [rebuild-site-now]

jobs:
  buildMachinekitSite:
    runs-on: ubuntu-latest
    steps:
      - name: Test egibility to tun
        run: |
          if [ "${{ secrets.KEYCODE}}x" = "${{ github.event.client_payload.authorization }}x" ]; then
            echo "Authorized to proceed."
          else
            echo "Authorization failed."
            exit 1
          fi

      - name: Checkout the change from Machinekit-docs
        uses: actions/checkout@v2
        with:
          repository: cerna/cerna-testing-actions
          ref: ${{ github.event.client_payload.ref }}
          path: to_build

      - name: Git SHA on which is the build requested
        run: echo ${{ github.event.client_payload.sha }}

      - name: Checkout this repository (GP)
        uses: actions/checkout@v2
        with:
          ref: master
          path: target
    
      - name: Get last commit author
        run: |
          echo ::set-env name=authormail::$(git log --format='%ae' -n 2 ${{ github.event.after }})
          echo ::set-env name=authorname::$(git log --format='%an' -n 2 ${{ github.event.after }})
        working-directory: ./to_build

      - name: Git log
        run: git log
        working-directory: ./to_build
      
      - name : GITHUB CONTEXT
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: echo "$GITHUB_CONTEXT"

      # Running the commands in ubuntu-master and not in Docker container because
      # of the age of the container -> It cannot be even build anymore
      - name: Run a Jekyll builder
        run: docker run -v $(pwd)/to_build:/work haberlerm/docker-jekyll-asciidoctor jekyll build --verbose --trace --config _config.yml,_config_devel.yml

      - name: Print newly created files
        run: ls -R to_build/_site -print1

      - name: Delete all files from Target
        run: find . -depth -not \( -path "./.git" -or -path "./.github" -or -path "." -or -path "./.git/*" -or -path "./.github/*" \) -print0 | xargs -0 -t -I '{}' rm  -d '{}'
        working-directory: ./target

      - name: Copy the newly generated site to Target
        run: cp -r to_build/_site/* target/

      - name: Create commit
        run: |
          git config --local user.email "$authormail"
          git config --local user.name "$authorname"
          echo "Author's name for the commit set to $authorname"
          echo "Author's mail for the commit set to $authormail"
          git add --all
          git commit -m "SHA causing build ${{ github.event.client_payload.SHA }}"
        working-directory: ./target

      - name: Push changes to master branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: target
          branch: master