name: Rebuild request
on:
  repository_dispatch:
    types: [rebuild-site-now]

jobs:
  myEvent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkou the change from Machinekit-docs
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          path: to_build
      - run: echo ${{ github.event.client_payload.sha }}

      - name: Checkout this repository (GP)
        uses: actions/checkout@v2
        with:
          ref: master
          path: target
    
      - name: Get last commit author
        run: |
          cd to_build
          echo ::set-env name=authormail::$(git log --format='%ae' -n 1 ${{ github.event.after }})
          echo ::set-env name=authorname::$(git log --format='%an' -n 1 ${{ github.event.after }})
          cd ..

      # Running the commands in ubuntu-master and not in Docker container because
      # of the age of the container -> It cannot be even build anymore
      - name: Run a Jekyll builder
        run: docker run -v $(pwd)/main-cat:/work haberlerm/docker-jekyll-asciidoctor jekyll build --verbose --trace --config _config.yml,_config_devel.yml

      - name: Print newly created files
        run: ls -R to_build/_site -print1

      - name: Delete all files from Target
        run: |
          cd target
          find . -depth -not \( -path "./.git" -or -path "./.github" -or -path "." -or -path "./.git/*" -or -path "./.github/*" \) -print0 | xargs -0 -t -I '{}' rm  -d '{}'
          cd ..

      - name: Copy the newly generated site to Target
        run: cp -r to_build/_site/* target/

      - name: Create commit
        run: |
          cd target
          git config --local user.email $authormail
          echo Author's mail for the commit set to $authormail
          git config --local user.name $authorname
          echo Author's name for the commit set to $authorname
          git add --all
          git commit -m "PULL request ID ${{ github.event.pull_request.id }}, URL ${{ github.event.pull_request.url }}, SHA ${{ github.event.pull_request.head.sha }} "
          cd ..

      - name: Push changes to master branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: target
          branch: master